-- --------------------------------------------------------
-- Servidor:                     127.0.0.1
-- Versão do servidor:           8.0.32 - MySQL Community Server - GPL
-- OS do Servidor:               Win64
-- HeidiSQL Versão:              12.4.0.6659
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Copiando dados para a tabela blogdogabu_db.changelog: ~32 rows (aproximadamente)
INSERT INTO `changelog` (`id`, `type`, `version`, `description`, `name`, `checksum`, `installed_by`, `installed_on`, `success`) VALUES
	(1, 2, '0', 'Empty schema found: rest_with_aps_net.', 'rest_with_aps_net', '', 'root', '2023-02-15 11:27:08', 1),
	(2, 0, '1', 'Create Table Person (39 ms)', 'V1__Create_Table_Person.sql', '3F22837EBA0B54536B3D01777D11FAA3', 'root', '2023-02-15 11:27:09', 1),
	(3, 0, '2', 'Populate Table Person (3 ms)', 'V2__Populate_Table_Person.sql', 'FC1E7FA557D5C37D4A864A76A22E0CAA', 'root', '2023-02-15 11:27:09', 1),
	(4, 0, '3', 'Create Table Books (13 ms)', 'V3__Create_Table_Books.sql', '0620370931614638A8E078DB509FA445', 'root', '2023-02-15 11:27:09', 1),
	(5, 0, '4', 'Insert Data In Books (5 ms)', 'V4__Insert_Data_In_Books.sql', '6837DDBE4AD4B12599CF1445F68D9205', 'root', '2023-02-15 11:27:09', 1),
	(6, 0, '5', 'Create Table Users (142 ms)', 'V5__Create_Table_Users.sql', 'E6356C056B401DFB6162C2F0394D5816', 'root', '2023-02-16 12:38:40', 1),
	(7, 0, '6', 'Insert Data In Users (10 ms)', 'V6__Insert_Data_In_Users.sql', 'DBBCB48EAC05AA2B95AB3B50A5CD3455', 'root', '2023-02-16 12:38:40', 1),
	(8, 0, '7', 'Alter Table Person (84 ms)', 'V7__Alter_Table_Person.sql', 'CD6F0D3D1B8B242A56DE8A56C1B2FFF6', 'root', '2023-02-16 16:36:22', 1),
	(9, 0, '8', 'Populate Person With Many (31 ms)', 'V8__Populate_Person_With_Many.sql', 'C7D6E621A34B0B37E1E4439773D71DDB', 'root', '2023-02-17 12:23:39', 1),
	(10, 0, '9', 'Create Table Posts (96 ms)', 'V9__Create_Table_Posts.sql', '88C1EC14B840021055088E2DC45D2135', 'root', '2023-02-22 11:54:59', 1),
	(11, 0, '10', 'Populate Posts With Many (17 ms)', 'V10__Populate_Posts_With_Many.sql', '3F464D9565ED471D8273336D12260D52', 'root', '2023-02-22 11:58:41', 0),
	(12, 0, '10', 'Populate Posts With Many (15 ms)', 'V10__Populate_Posts_With_Many.sql', '35457B0963A7B647977124B70666D262', 'root', '2023-02-22 12:05:16', 0),
	(13, 0, '10', 'Populate Posts With Many (12 ms)', 'V10__Populate_Posts_With_Many.sql', '3F464D9565ED471D8273336D12260D52', 'root', '2023-02-22 12:06:44', 0),
	(14, 0, '11', 'Create Table Posts (26 ms)', 'V11__Create_Table_Posts.sql', 'ABC30156925D1A9814F442A6E49C8321', 'root', '2023-02-22 12:08:42', 1),
	(15, 0, '12', 'Populate Posts With Many (45 ms)', 'V12__Populate_Posts_With_Many.sql', '3F464D9565ED471D8273336D12260D52', 'root', '2023-02-22 12:09:23', 1),
	(16, 0, '13', 'Create Table Comments (14 ms)', 'V13__Create_Table_Comments.sql', '24DE3D69BFFB75AD1C676173F01B5A0B', 'root', '2023-02-24 11:59:21', 0),
	(17, 0, '13', 'Create Table Comments (10 ms)', 'V13__Create_Table_Comments.sql', '75ADDFCA33E64D82B260F2B861C6681D', 'root', '2023-02-24 12:01:33', 0),
	(18, 0, '13', 'Create Table Comments (66 ms)', 'V13__Create_Table_Comments.sql', '21FCBDE827DD345EAE6971836B02A067', 'root', '2023-02-24 12:03:32', 1),
	(19, 0, '14', 'Create Table Comments (78 ms)', 'V14__Create_Table_Comments.sql', '9A96BE77646E3DB49701AC947D4C60D3', 'root', '2023-02-24 12:20:49', 1),
	(20, 0, '15', 'Alter Table Comments (20 ms)', 'V15__Alter_Table_Comments.sql', '4E4C873BCC506A2A6A8DC33987FEDB4E', 'root', '2023-02-24 12:26:11', 0),
	(21, 0, '15', 'Alter Table Comments (34 ms)', 'V15__Alter_Table_Comments.sql', '53F877B9161B447FACD6C44CA4B26AC5', 'root', '2023-02-24 12:27:03', 1),
	(22, 0, '16', 'Populate Comments With Many (21 ms)', 'V16__Populate_Comments_With_Many.sql', 'D524E7D1605148C2B556E85FBF59BAB3', 'root', '2023-02-24 13:05:05', 0),
	(23, 0, '16', 'Populate Comments With Many (22 ms)', 'V16__Populate_Comments_With_Many.sql', 'B7E6037F60051CF3FE39BE6C6150D82E', 'root', '2023-02-24 13:06:50', 1),
	(24, 0, '17', 'Populate Comments With Many (49 ms)', 'V17__Populate_Comments_With_Many.sql', '4EB70C5C1C335FA158C47AEDB49E494F', 'root', '2023-02-24 16:45:35', 1),
	(25, 0, '18', 'Alter Table Posts (87 ms)', 'V18__Alter_Table_Posts.sql', 'CD50BCC1F3C9DDE334A246A4A1A6AE5A', 'root', '2023-02-28 13:32:53', 1),
	(26, 0, '19', 'Alter Table Posts (86 ms)', 'V19__Alter_Table_Posts.sql', 'AF9B39304AA6415A96A6630BBC8900D6', 'root', '2023-02-28 16:10:52', 1),
	(27, 0, '20', 'Create Table Posts (50 ms)', 'V20__Create_Table_Posts.sql', 'F9998B7BB141391680032CD217E9616D', 'root', '2023-02-28 16:37:55', 1),
	(28, 0, '21', 'Create Table Files (17 ms)', 'V21__Create_Table_Files.sql', 'C02C2E18907162A5F07F8B46DC127C39', 'root', '2023-03-01 11:50:26', 0),
	(29, 0, '21', 'Create Table Files (15 ms)', 'V21__Create_Table_Files.sql', 'C02C2E18907162A5F07F8B46DC127C39', 'root', '2023-03-01 11:52:00', 0),
	(30, 0, '21', 'Create Table Files (24 ms)', 'V21__Create_Table_Files.sql', '991F72BC8B409CEB3706E9ADB6C014E3', 'root', '2023-03-01 11:52:39', 0),
	(31, 0, '21', 'Create Table Files (29 ms)', 'V21__Create_Table_Files.sql', '6750C4AFF113208E2A31F167D61CA7F0', 'root', '2023-03-01 11:54:02', 0),
	(32, 0, '21', 'Create Table Files (80 ms)', 'V21__Create_Table_Files.sql', 'C6B1F12CA788763FAAD38FDCA9078E14', 'root', '2023-03-01 11:54:46', 1),
	(33, 0, '22', 'Alter Table Posts (85 ms)', 'V22__Alter_Table_Posts.sql', '128822398EA896AF6AD0A62CB9E5F34E', 'root', '2023-03-01 14:29:19', 1),
	(34, 0, '23', 'Alter Table Posts (53 ms)', 'V23__Alter_Table_Posts.sql', '6D6F94C30BF2B3A68858A3993DAA11C5', 'root', '2023-03-01 15:39:36', 1);

-- Copiando dados para a tabela blogdogabu_db.comments: ~131 rows (aproximadamente)
INSERT INTO `comments` (`id`, `content`, `post_date`, `person_name`, `posts_id`) VALUES
	(1, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2022-03-21 02:12:05.000000', 'Matsoft', 1),
	(2, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2022-08-15 06:44:03.000000', 'Subin', 2),
	(3, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-08-01 02:43:07.000000', 'Ventosanzap', 3),
	(4, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2022-07-24 07:51:14.000000', 'Subin', 4),
	(5, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2022-07-26 20:10:22.000000', 'Transcof', 5),
	(6, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '2022-06-24 04:23:01.000000', 'Transcof', 6),
	(7, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '2022-07-21 00:39:28.000000', 'Latlux', 7),
	(8, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2022-03-30 18:15:59.000000', 'Zontrax', 8),
	(9, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2022-04-13 20:52:50.000000', 'Overhold', 9),
	(10, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-10-19 12:31:29.000000', 'Cardguard', 10),
	(11, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2022-07-02 01:11:22.000000', 'Latlux', 11),
	(12, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2022-04-20 13:07:29.000000', 'Veribet', 12),
	(13, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.', '2022-08-03 22:49:04.000000', 'It', 13),
	(14, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2022-12-21 04:07:03.000000', 'Y-find', 14),
	(15, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2022-06-08 08:18:15.000000', 'Zaam-Dox', 15),
	(16, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2022-02-26 08:25:37.000000', 'Pannier', 16),
	(17, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2022-08-09 19:27:47.000000', 'Hatity', 17),
	(18, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2022-04-19 02:35:23.000000', 'Biodex', 18),
	(19, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2022-04-22 05:43:25.000000', 'Fixflex', 19),
	(20, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2022-07-04 13:17:13.000000', 'Otcom', 20),
	(21, 'amet tempor', '2022-03-21 02:12:05.000000', 'anim Excepteur', 1),
	(22, 'amet tempor', '2022-03-21 02:12:05.000000', 'AAAAAAAAAAAAAA Excepteur', 1),
	(23, 'aaaaabbbbbb', '2023-02-24 14:57:38.598000', 'Migueleell', 1),
	(24, 'Liliki\n', '2023-02-24 14:59:49.155000', 'title', 1),
	(25, 'Liliki\n', '2023-02-24 14:59:53.923000', 'title', 1),
	(26, 'Liliki\n', '2023-02-24 14:59:54.066000', 'title', 1),
	(27, 'Liliki\n', '2023-02-24 14:59:54.211000', 'title', 1),
	(28, 'Liliki\n', '2023-02-24 14:59:54.317000', 'title', 1),
	(29, 'Liliki\n', '2023-02-24 14:59:54.411000', 'title', 1),
	(30, 'oi', '2023-02-24 16:09:57.099000', 'Gabu', 1),
	(31, 'oi', '2023-02-24 16:09:57.641000', 'Gabu', 1),
	(32, 'amet tempor', '2022-03-21 02:12:05.000000', 'AAAAAAAAAAAAAA Excepteur', 18),
	(33, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2021-01-19 03:30:17.000000', 'Gaylene', 1),
	(34, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2020-10-22 05:58:47.000000', 'Carolee', 2),
	(35, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2021-12-18 14:29:12.000000', 'Cesaro', 3),
	(36, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '2020-03-21 16:50:38.000000', 'Karee', 4),
	(37, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2021-08-24 09:21:40.000000', 'Marthe', 5),
	(38, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2021-03-11 14:29:39.000000', 'Lotty', 6),
	(39, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2023-01-25 11:35:00.000000', 'Tamar', 7),
	(40, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2021-07-08 00:57:02.000000', 'Gweneth', 8),
	(41, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2021-04-17 19:47:55.000000', 'Audie', 9),
	(42, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '2020-04-30 21:00:25.000000', 'Cally', 10),
	(43, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2021-08-31 20:16:23.000000', 'Raddy', 11),
	(44, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2021-11-19 15:15:38.000000', 'Odo', 12),
	(45, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2022-11-15 06:34:16.000000', 'Morey', 13),
	(46, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2019-10-31 06:29:11.000000', 'Arch', 14),
	(47, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', '2022-11-27 04:25:08.000000', 'Blaire', 15),
	(48, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2022-10-18 02:57:45.000000', 'Tildie', 16),
	(49, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2022-09-22 11:20:44.000000', 'Samantha', 17),
	(50, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2020-03-27 19:45:08.000000', 'Anjela', 18),
	(51, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2021-04-20 07:01:20.000000', 'Elden', 19),
	(52, 'Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '2022-04-29 22:44:08.000000', 'Raphaela', 20),
	(53, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2020-05-24 21:35:03.000000', 'Shir', 21),
	(54, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2023-02-14 09:18:06.000000', 'Martynne', 22),
	(55, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2020-02-26 18:21:40.000000', 'Franky', 23),
	(56, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2022-12-16 08:21:30.000000', 'Orelie', 24),
	(57, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2020-10-30 15:47:59.000000', 'Cyril', 25),
	(58, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2020-06-21 23:27:13.000000', 'Juliana', 26),
	(59, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2020-08-05 17:59:56.000000', 'Derby', 27),
	(60, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2022-08-31 09:40:41.000000', 'Jobina', 28),
	(61, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2020-05-05 14:50:07.000000', 'Erasmus', 29),
	(62, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2021-02-04 17:27:59.000000', 'Juliane', 30),
	(63, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2021-12-01 04:32:02.000000', 'Sheffy', 31),
	(64, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2020-11-08 17:18:22.000000', 'Joel', 32),
	(65, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2020-11-15 00:33:22.000000', 'Christian', 33),
	(66, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2022-06-13 16:00:26.000000', 'Roosevelt', 34),
	(67, 'In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '2019-12-11 17:13:51.000000', 'Billie', 35),
	(68, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2023-02-23 10:20:14.000000', 'Brittaney', 36),
	(69, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2021-01-21 09:25:25.000000', 'Kirstyn', 37),
	(70, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2020-03-18 20:05:44.000000', 'Frans', 38),
	(71, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2020-10-18 08:11:09.000000', 'Cass', 39),
	(72, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2021-01-07 22:56:22.000000', 'Chaddy', 40),
	(73, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2020-01-15 15:33:44.000000', 'Berthe', 41),
	(74, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2022-12-25 00:19:22.000000', 'Parrnell', 42),
	(75, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2019-10-17 08:03:05.000000', 'Ferguson', 43),
	(76, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '2023-01-16 18:46:45.000000', 'Quintin', 44),
	(77, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.', '2021-01-16 10:09:13.000000', 'Rusty', 45),
	(78, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2022-06-17 20:24:43.000000', 'Betteanne', 46),
	(79, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2022-11-27 20:51:50.000000', 'Dory', 47),
	(80, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.', '2020-08-13 18:38:30.000000', 'Tynan', 48),
	(81, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2020-12-28 14:21:12.000000', 'Ashbey', 49),
	(82, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2022-03-21 08:08:19.000000', 'Amandy', 50),
	(83, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2022-04-19 03:11:17.000000', 'Waite', 51),
	(84, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2019-11-19 20:42:49.000000', 'Ken', 52),
	(85, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-11-18 21:55:48.000000', 'Linc', 53),
	(86, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2020-04-11 23:58:43.000000', 'Fairlie', 54),
	(87, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.', '2021-11-15 03:08:50.000000', 'Richardo', 55),
	(88, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2021-05-03 21:48:13.000000', 'Heywood', 56),
	(89, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2021-07-18 11:33:57.000000', 'Dorine', 57),
	(90, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2022-04-30 13:54:18.000000', 'Rea', 58),
	(91, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2020-08-27 13:35:36.000000', 'Nikos', 59),
	(92, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2021-01-07 23:03:20.000000', 'Armand', 60),
	(93, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2022-09-29 08:57:34.000000', 'Rozelle', 61),
	(94, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '2021-01-25 17:15:34.000000', 'Sandye', 62),
	(95, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2019-10-30 03:16:49.000000', 'Ranique', 63),
	(96, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2020-02-26 09:55:51.000000', 'Adams', 64),
	(97, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', '2020-03-02 11:09:17.000000', 'Yolanthe', 65),
	(98, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2019-10-22 21:16:44.000000', 'Dulsea', 66),
	(99, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2020-02-28 19:41:01.000000', 'Haskel', 67),
	(100, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2020-01-01 08:45:24.000000', 'Ilario', 68),
	(101, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2022-02-16 08:17:14.000000', 'Skyler', 69),
	(102, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2021-08-07 06:46:43.000000', 'Maureene', 70),
	(103, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2021-06-03 21:40:48.000000', 'Lynna', 71),
	(104, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2020-12-25 14:43:26.000000', 'Vi', 72),
	(105, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '2021-05-28 19:52:52.000000', 'Artemas', 73),
	(106, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2021-11-27 01:19:33.000000', 'Jemie', 74),
	(107, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', '2019-12-01 06:41:02.000000', 'Peri', 75),
	(108, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2021-11-07 13:32:23.000000', 'Norman', 76),
	(109, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2021-03-23 17:49:00.000000', 'Abagail', 77),
	(110, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2022-06-02 05:35:42.000000', 'Kassi', 78),
	(111, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2022-04-08 01:09:01.000000', 'Marnie', 79),
	(112, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2022-04-22 00:48:40.000000', 'Kinny', 80),
	(113, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2020-01-17 09:49:46.000000', 'Gay', 81),
	(114, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2022-05-08 08:48:39.000000', 'Verene', 82),
	(115, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2019-12-11 03:49:55.000000', 'Janka', 83),
	(116, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2022-01-18 02:21:03.000000', 'Selestina', 84),
	(117, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2023-01-10 04:14:56.000000', 'Wilmar', 85),
	(118, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.', '2022-09-11 11:38:14.000000', 'Deny', 86),
	(119, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2022-10-01 06:54:23.000000', 'Nataline', 87),
	(120, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.', '2020-01-27 01:41:50.000000', 'Flo', 88),
	(121, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2021-08-15 17:01:29.000000', 'Glory', 89),
	(122, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2020-05-17 15:49:24.000000', 'Suzy', 90),
	(123, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2021-04-09 19:36:31.000000', 'Imogene', 91),
	(124, 'In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2021-05-20 13:18:33.000000', 'Flossie', 92),
	(125, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2020-11-13 17:14:48.000000', 'Thomasina', 93),
	(126, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2021-04-27 09:40:48.000000', 'Arther', 94),
	(127, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2020-08-17 08:49:16.000000', 'Afton', 95),
	(128, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2020-02-06 06:08:49.000000', 'Flory', 96),
	(129, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2021-05-20 22:27:08.000000', 'Haley', 97),
	(130, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2020-09-08 11:11:08.000000', 'Antin', 98),
	(131, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '2021-05-31 09:47:21.000000', 'Mikol', 99),
	(132, 'EEEEEEEEELIKE', '2023-02-24 16:46:30.317000', 'Jermano', 3),
	(134, 'AAaaaaaaaaaaaaaaaaaaaaAAAAAAAAAAAA', '2023-02-27 11:35:15.680000', 'O estagiário', 4),
	(135, 'B', '2023-02-27 11:41:16.376000', 'O estagiário', 4),
	(136, 'oi', '2023-02-27 11:49:13.253000', 'Gabu', 4),
	(137, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2023-02-27 11:49:29.716000', 'a', 4),
	(138, 'OioI', '2023-02-27 14:02:17.073000', 'Gabu', 40),
	(139, '', '2023-02-28 13:06:25.442000', '', 75),
	(140, 'a', '2023-02-28 16:08:41.322000', 'Gostei', 101),
	(141, '                if (this.VF) {\n                    const fd = new FormData();\n                    fd.append(\'file\', this.arquivo, this.arquivo.name)\n                    axios.post(\'https://localhost:51427/api/File/v1/uploadFile\', fd, {\n                        onUploadProgress: uploadEvent => {\n                            console.log(\'Progresso: \' + Math.round(uploadEvent.loaded / uploadEvent.total * 100) + \'%\')\n                        }\n                    }).then(res => {\n                        console.log(res)\n                    });\n                    this.arquivo = null;\n                }', '2023-02-28 16:30:21.403000', 'Gabu', 5),
	(142, 'Muito bom!\n', '2023-03-02 16:24:31.535000', 'Gabu', 36),
	(143, 'Testando comentario', '2023-03-02 16:45:54.633000', 'Teste', 50);

-- Copiando dados para a tabela blogdogabu_db.files: ~0 rows (aproximadamente)

-- Copiando dados para a tabela blogdogabu_db.person: ~305 rows (aproximadamente)
INSERT INTO `person` (`id`, `first_name`, `last_name`, `address`, `gender`, `enabled`) VALUES
	(1, 'Ayrton', 'Senna', 'São Paulo - Brasil', 'Male', b'1'),
	(2, 'Leonardo', 'da Vinci', 'Anchiano - Italy', 'Male', b'1'),
	(3, 'Mahatma', 'Gandhi', 'Porbandar - India', 'Male', b'1'),
	(4, 'Mohamed Ali', 'Gandhi', 'Kentucky - USA', 'Male', b'1'),
	(5, 'Nelson', 'Mandela', 'Mvezo - South Africa', 'Male', b'1'),
	(6, 'Jedd', 'Klossmann', '5 Pearson Pass', 'Male', b'0'),
	(7, 'Dolorita', 'Quickenden', '38 Morning Park', 'Female', b'0'),
	(8, 'Dimitri', 'Arney', '8 Esch Hill', 'Male', b'0'),
	(9, 'Emmery', 'Meadowcroft', '2068 Schmedeman Circle', 'Male', b'0'),
	(10, 'Frasier', 'Sline', '7 Redwing Point', 'Male', b'0'),
	(11, 'Tarrance', 'Van de Vlies', '27858 Haas Pass', 'Male', b'0'),
	(12, 'Perkin', 'O\'Shaughnessy', '6 Marcy Crossing', 'Male', b'1'),
	(13, 'Micheline', 'O\'Doghesty', '8869 Scofield Avenue', 'Female', b'0'),
	(14, 'Adelbert', 'Siburn', '95988 Melrose Point', 'Male', b'0'),
	(15, 'Norene', 'Gatherell', '84065 Merry Court', 'Female', b'1'),
	(16, 'Minta', 'Gotcliff', '937 Starling Drive', 'Female', b'0'),
	(17, 'Elita', 'Sherrum', '92 Golf Point', 'Female', b'1'),
	(18, 'Gris', 'Macallam', '2288 Fuller Terrace', 'Male', b'0'),
	(19, 'Silva', 'Piris', '70 Dwight Point', 'Female', b'1'),
	(20, 'Karilynn', 'Pesterfield', '75 Lerdahl Court', 'Female', b'0'),
	(21, 'Brynn', 'Ramard', '2 Little Fleur Hill', 'Female', b'0'),
	(22, 'Nanete', 'Boler', '646 Maryland Way', 'Female', b'0'),
	(23, 'Dane', 'Jarvis', '120 8th Place', 'Male', b'1'),
	(24, 'Nyssa', 'Pauletti', '426 Eagle Crest Lane', 'Female', b'0'),
	(25, 'Aile', 'Kynastone', '62 Mayfield Place', 'Female', b'1'),
	(26, 'Carmella', 'Grelik', '6294 Michigan Pass', 'Female', b'1'),
	(27, 'Marty', 'Perris', '484 Schlimgen Center', 'Male', b'0'),
	(28, 'Michal', 'Hackelton', '12 Muir Center', 'Male', b'1'),
	(29, 'Mortimer', 'Hoyland', '24129 Surrey Parkway', 'Male', b'1'),
	(30, 'Cathee', 'Pagitt', '015 Brickson Park Alley', 'Female', b'1'),
	(31, 'Emogene', 'Dominici', '304 Eagan Center', 'Female', b'1'),
	(32, 'Leora', 'Brookshaw', '39093 Scott Lane', 'Female', b'1'),
	(33, 'Konrad', 'Weldon', '00 Old Gate Point', 'Male', b'1'),
	(34, 'Peria', 'Fassan', '03009 Waywood Road', 'Female', b'0'),
	(35, 'Anderson', 'Allport', '4 Colorado Plaza', 'Male', b'1'),
	(36, 'Job', 'Philpott', '19 Delaware Alley', 'Male', b'1'),
	(37, 'Adrea', 'Hellwich', '408 Talmadge Way', 'Female', b'1'),
	(38, 'Lydon', 'Fenelow', '325 Muir Plaza', 'Male', b'0'),
	(39, 'Reagan', 'Dinkin', '0275 Colorado Plaza', 'Male', b'1'),
	(40, 'Lazar', 'Boniface', '94130 Basil Center', 'Male', b'1'),
	(41, 'Bette', 'Eilert', '128 Vidon Street', 'Female', b'1'),
	(42, 'Fabiano', 'Tansly', '314 Melody Park', 'Male', b'1'),
	(43, 'Mommy', 'Mengo', '2 Parkside Center', 'Female', b'1'),
	(44, 'Bartholomeo', 'Cockerill', '0 Sage Park', 'Male', b'1'),
	(45, 'Filippo', 'MacInnes', '80 Waubesa Avenue', 'Male', b'1'),
	(46, 'Kingston', 'Botler', '0585 Bultman Trail', 'Male', b'0'),
	(47, 'Ritchie', 'McReedy', '7644 Mcbride Road', 'Male', b'1'),
	(48, 'Xever', 'Horick', '076 Bobwhite Point', 'Male', b'0'),
	(49, 'Kyrstin', 'Pyrke', '5 Columbus Lane', 'Female', b'0'),
	(50, 'Filia', 'Baldi', '0749 Mosinee Way', 'Female', b'0'),
	(51, 'Adriano', 'Marcinkus', '46 Shasta Court', 'Male', b'0'),
	(52, 'Andree', 'Pipes', '8 Randy Crossing', 'Female', b'1'),
	(53, 'Atlanta', 'Very', '52 Spaight Place', 'Female', b'0'),
	(54, 'Earl', 'Drewett', '8693 Scofield Trail', 'Male', b'1'),
	(55, 'Will', 'Biggins', '60 Manufacturers Hill', 'Male', b'0'),
	(56, 'Eveline', 'Hughes', '2 Granby Street', 'Female', b'1'),
	(57, 'Bambi', 'Petts', '511 Bellgrove Point', 'Female', b'1'),
	(58, 'Ellissa', 'Littlekit', '80769 Superior Plaza', 'Female', b'1'),
	(59, 'Tann', 'Sykes', '175 Westend Trail', 'Male', b'0'),
	(60, 'Claudia', 'Semple', '23 Spenser Road', 'Female', b'1'),
	(61, 'Albert', 'Kwietak', '0 Sycamore Point', 'Male', b'1'),
	(62, 'Hilda', 'Makin', '76549 Kensington Circle', 'Female', b'1'),
	(63, 'Gavin', 'Rossant', '0319 Muir Park', 'Male', b'1'),
	(64, 'Delaney', 'Reeveley', '91 Glacier Hill Hill', 'Male', b'1'),
	(65, 'Donaugh', 'Piddlesden', '683 Arapahoe Avenue', 'Male', b'1'),
	(66, 'Gilbertine', 'Alessandrini', '22771 1st Trail', 'Female', b'1'),
	(67, 'Arnaldo', 'Nelm', '356 Service Center', 'Male', b'1'),
	(68, 'Daisi', 'Toombs', '10851 Crownhardt Park', 'Female', b'1'),
	(69, 'Leah', 'Drinkale', '0 Elmside Park', 'Female', b'0'),
	(70, 'Jacquenetta', 'Gretton', '24 Paget Junction', 'Female', b'0'),
	(71, 'Melisa', 'Rottger', '9992 Calypso Street', 'Female', b'1'),
	(72, 'Yevette', 'Mapston', '027 Gateway Circle', 'Female', b'0'),
	(73, 'Delphinia', 'Spurgin', '712 Kedzie Center', 'Female', b'1'),
	(74, 'Garry', 'Jeromson', '781 Michigan Crossing', 'Male', b'1'),
	(75, 'Harri', 'Godley', '4483 Brentwood Junction', 'Female', b'1'),
	(76, 'James', 'Jobern', '57649 Claremont Point', 'Male', b'1'),
	(77, 'Rayna', 'Sale', '040 Carberry Park', 'Female', b'1'),
	(78, 'Ernie', 'Brauner', '92630 Montana Place', 'Male', b'1'),
	(79, 'Cindra', 'Alcorn', '957 Carpenter Pass', 'Female', b'0'),
	(80, 'Cami', 'Buessen', '4980 Oak Terrace', 'Female', b'1'),
	(81, 'Tully', 'Rounsefell', '46 Lighthouse Bay Plaza', 'Male', b'1'),
	(82, 'Ede', 'Van Waadenburg', '4045 Reindahl Point', 'Female', b'1'),
	(83, 'Isiahi', 'Spindler', '2690 Gale Trail', 'Male', b'0'),
	(84, 'Jerrilee', 'Fermoy', '92 Nevada Circle', 'Female', b'0'),
	(85, 'Bessie', 'Nardi', '8472 Anderson Road', 'Female', b'1'),
	(86, 'Emeline', 'Wasselin', '1 Knutson Avenue', 'Female', b'0'),
	(87, 'Cassie', 'Ende', '98295 Straubel Junction', 'Male', b'1'),
	(88, 'Alexandros', 'Press', '234 Jana Road', 'Male', b'1'),
	(89, 'Lisle', 'Langrick', '8226 Everett Circle', 'Male', b'1'),
	(90, 'Corbet', 'Parham', '9 Swallow Park', 'Male', b'0'),
	(91, 'Willabella', 'Ricardon', '58125 Westport Way', 'Female', b'0'),
	(92, 'Connie', 'Shutler', '99 Holmberg Hill', 'Male', b'0'),
	(93, 'Pooh', 'Weiser', '236 Eastwood Point', 'Male', b'0'),
	(94, 'Patricia', 'Gerhold', '373 Continental Junction', 'Female', b'1'),
	(95, 'Yorgos', 'Lampett', '85471 Memorial Lane', 'Male', b'0'),
	(96, 'Leonidas', 'Roke', '17 Talmadge Alley', 'Male', b'0'),
	(97, 'Noak', 'Giabucci', '93193 Lunder Place', 'Male', b'0'),
	(98, 'Kin', 'MacVean', '55 Declaration Point', 'Male', b'0'),
	(99, 'Nelly', 'Ondricek', '36502 Kim Avenue', 'Female', b'0'),
	(100, 'Julie', 'Trevers', '540 Pennsylvania Street', 'Male', b'1'),
	(101, 'Eugenius', 'Skinn', '90 Lerdahl Place', 'Male', b'1'),
	(102, 'Donnie', 'Kleinhaut', '34 Lakewood Gardens Trail', 'Male', b'0'),
	(103, 'Ag', 'Jirasek', '93 Anthes Circle', 'Female', b'1'),
	(104, 'Eloise', 'Attfield', '4 Barnett Hill', 'Female', b'1'),
	(105, 'Saw', 'Dumbare', '8 Packers Hill', 'Male', b'1'),
	(106, 'Dagny', 'Beran', '49 Hazelcrest Trail', 'Male', b'1'),
	(107, 'Jay', 'McQuaker', '78821 Hanover Parkway', 'Male', b'0'),
	(108, 'Ailee', 'Cattemull', '5 Thompson Pass', 'Female', b'0'),
	(109, 'Leanna', 'Gorden', '03 Forest Run Park', 'Female', b'0'),
	(110, 'Wandis', 'McNerlin', '81412 Loftsgordon Place', 'Female', b'1'),
	(111, 'Roldan', 'Leahey', '115 Pond Circle', 'Male', b'0'),
	(112, 'Mignon', 'Idenden', '0024 Dawn Hill', 'Female', b'1'),
	(113, 'Edlin', 'Leas', '3 Division Place', 'Male', b'1'),
	(114, 'Rafaellle', 'Brayford', '55330 Kingsford Pass', 'Male', b'0'),
	(115, 'Arni', 'Duffett', '00120 Muir Drive', 'Male', b'1'),
	(116, 'Lindy', 'Galgey', '22020 Superior Alley', 'Male', b'1'),
	(117, 'Anny', 'Cavee', '76012 Carberry Point', 'Female', b'0'),
	(118, 'Elnore', 'Ellph', '05246 American Ash Avenue', 'Female', b'0'),
	(119, 'Halli', 'Josephoff', '6 Porter Lane', 'Female', b'0'),
	(120, 'Ashia', 'Westoll', '02 Spenser Alley', 'Female', b'0'),
	(121, 'Pebrook', 'Inchley', '020 Birchwood Center', 'Male', b'1'),
	(122, 'Paton', 'Marczyk', '31148 Chive Parkway', 'Male', b'1'),
	(123, 'Lauritz', 'Shakelady', '61923 Nobel Court', 'Male', b'1'),
	(124, 'Ingra', 'Jeenes', '0 Schmedeman Street', 'Male', b'0'),
	(125, 'Thoma', 'Duddin', '1144 Spenser Way', 'Male', b'0'),
	(126, 'Sylvia', 'Musk', '6 Melby Place', 'Female', b'0'),
	(127, 'Carlie', 'Williamson', '7 Dakota Avenue', 'Male', b'1'),
	(128, 'Kacy', 'Gillies', '6997 Morningstar Lane', 'Female', b'0'),
	(129, 'Horatius', 'Curness', '132 Lyons Crossing', 'Male', b'1'),
	(130, 'Nananne', 'Calbert', '9 Steensland Park', 'Female', b'0'),
	(131, 'Nikolia', 'Growcock', '0174 Mcguire Park', 'Female', b'0'),
	(132, 'Godard', 'Flooks', '53 Forest Run Street', 'Male', b'0'),
	(133, 'Glynis', 'Swyndley', '587 Pond Parkway', 'Female', b'1'),
	(134, 'Maria', 'Diggins', '06780 2nd Parkway', 'Female', b'1'),
	(135, 'Collin', 'Gooch', '56 Mayer Court', 'Male', b'1'),
	(136, 'Lark', 'Creamen', '333 Mariners Cove Drive', 'Female', b'1'),
	(137, 'Bettye', 'Minchinton', '94 Upham Center', 'Female', b'0'),
	(138, 'Iorgos', 'Vasilov', '99956 Crowley Trail', 'Male', b'1'),
	(139, 'Hugh', 'De Biaggi', '93018 Melby Way', 'Male', b'0'),
	(140, 'Winny', 'Gierok', '7796 Becker Crossing', 'Female', b'0'),
	(141, 'Giovanni', 'Damsell', '20 Lawn Court', 'Male', b'0'),
	(142, 'Sigfried', 'Elcock', '93059 Dawn Hill', 'Male', b'0'),
	(143, 'Rasla', 'Jemmison', '07301 Sundown Crossing', 'Female', b'1'),
	(144, 'Craig', 'Crasswell', '51 Corscot Parkway', 'Male', b'0'),
	(145, 'Jarrod', 'Sponder', '79533 Anzinger Drive', 'Male', b'0'),
	(146, 'Law', 'Imloch', '2000 Warrior Drive', 'Male', b'0'),
	(147, 'Robb', 'Tibols', '32 Blue Bill Park Parkway', 'Male', b'1'),
	(148, 'Stephanus', 'Hummerston', '47595 Manley Alley', 'Male', b'1'),
	(149, 'Deidre', 'Bunny', '00 Arkansas Park', 'Female', b'0'),
	(150, 'Vivian', 'Trulocke', '282 Caliangt Center', 'Female', b'1'),
	(151, 'Norri', 'Kroll', '78232 Bellgrove Road', 'Female', b'0'),
	(152, 'Calley', 'Nehls', '110 Bunting Avenue', 'Female', b'0'),
	(153, 'Thatch', 'Cooksley', '719 Elmside Way', 'Male', b'0'),
	(154, 'Phylys', 'Creelman', '0720 8th Park', 'Female', b'1'),
	(155, 'Abeu', 'Hullins', '95990 Ludington Point', 'Male', b'0'),
	(156, 'Costanza', 'Karlowicz', '2404 Marquette Point', 'Female', b'0'),
	(157, 'Morganica', 'Sixsmith', '11997 Delladonna Pass', 'Female', b'1'),
	(158, 'Amelie', 'Moorhead', '935 Quincy Center', 'Female', b'0'),
	(159, 'Gwennie', 'Levecque', '7 Sloan Lane', 'Female', b'0'),
	(160, 'Arch', 'Keher', '05715 Oak Junction', 'Male', b'1'),
	(161, 'Annelise', 'Cruce', '571 Meadow Vale Center', 'Female', b'1'),
	(162, 'Jocko', 'Seabrocke', '0103 Ridgeview Pass', 'Male', b'0'),
	(163, 'Ernie', 'Pavlik', '16 Hansons Center', 'Male', b'0'),
	(164, 'Devora', 'Paty', '92 Stone Corner Crossing', 'Female', b'0'),
	(165, 'Solly', 'Bolding', '0 Farragut Pass', 'Male', b'0'),
	(166, 'Raimondo', 'Dorwood', '8 Kingsford Court', 'Male', b'0'),
	(167, 'Luisa', 'Portchmouth', '072 South Plaza', 'Female', b'0'),
	(168, 'Chandler', 'Sweetsur', '09 Lakewood Way', 'Male', b'1'),
	(169, 'Adria', 'Sandercroft', '32325 Hermina Pass', 'Female', b'1'),
	(170, 'Lucio', 'Bruckent', '77 Fisk Parkway', 'Male', b'0'),
	(171, 'Chucho', 'Meffin', '694 Novick Lane', 'Male', b'1'),
	(172, 'Amandy', 'Haugg', '866 Jana Lane', 'Female', b'1'),
	(173, 'Chet', 'Giovannini', '6405 Northland Trail', 'Male', b'0'),
	(174, 'Mickey', 'Rudiger', '33 Mccormick Crossing', 'Male', b'0'),
	(175, 'Griswold', 'Belliveau', '97 Golf View Court', 'Male', b'0'),
	(176, 'Robert', 'Janks', '2 Northridge Point', 'Male', b'1'),
	(177, 'Yule', 'Henke', '1 Pepper Wood Terrace', 'Male', b'1'),
	(178, 'Conn', 'Rennebeck', '02208 Farragut Pass', 'Male', b'0'),
	(179, 'Ev', 'Lacer', '9 Welch Way', 'Male', b'1'),
	(180, 'Kikelia', 'Deveral', '7010 Annamark Trail', 'Female', b'0'),
	(181, 'Jonah', 'Kurton', '581 Myrtle Way', 'Male', b'1'),
	(182, 'Shep', 'O\'Leahy', '3 Crescent Oaks Street', 'Male', b'1'),
	(183, 'Aloysius', 'Beale', '81 Mockingbird Plaza', 'Male', b'0'),
	(184, 'Joly', 'Brunnstein', '75 Rowland Trail', 'Female', b'1'),
	(185, 'Rosemarie', 'Dome', '55489 Park Meadow Center', 'Female', b'0'),
	(186, 'Tad', 'Jaqueminet', '5 Goodland Street', 'Male', b'0'),
	(187, 'Shell', 'Pollastrino', '0346 Portage Plaza', 'Female', b'0'),
	(188, 'Tonnie', 'Siebert', '183 Buhler Court', 'Male', b'1'),
	(189, 'Francisca', 'Sinott', '96301 Petterle Parkway', 'Female', b'0'),
	(190, 'Trstram', 'Jenno', '18 Thierer Parkway', 'Male', b'1'),
	(191, 'Elita', 'Cheeld', '27941 Hauk Junction', 'Female', b'0'),
	(192, 'Penelopa', 'Sreenan', '8280 Lerdahl Center', 'Female', b'0'),
	(193, 'Collete', 'Tees', '1 Johnson Terrace', 'Female', b'0'),
	(194, 'Saxe', 'Balharry', '09 Warner Junction', 'Male', b'1'),
	(195, 'Brandy', 'Eisig', '92 Arapahoe Trail', 'Male', b'0'),
	(196, 'Jeremias', 'Jzhakov', '9 Buell Drive', 'Male', b'0'),
	(197, 'Tony', 'Allmen', '24 Division Avenue', 'Female', b'0'),
	(198, 'Pepito', 'Vasilkov', '93534 Anderson Avenue', 'Male', b'1'),
	(199, 'Bruce', 'Fesby', '65 Farwell Trail', 'Male', b'0'),
	(200, 'Laure', 'Garioch', '1 Forster Hill', 'Female', b'0'),
	(201, 'Donelle', 'Turland', '03 Melrose Hill', 'Female', b'1'),
	(202, 'Bobbette', 'Castille', '3 Anthes Center', 'Female', b'1'),
	(203, 'Aylmer', 'Stampfer', '1 Norway Maple Road', 'Male', b'1'),
	(204, 'Karyl', 'Brimner', '9 Thierer Junction', 'Female', b'0'),
	(205, 'Frasquito', 'Hawket', '94 Maryland Court', 'Male', b'0'),
	(206, 'Davidde', 'Sansam', '5262 Susan Point', 'Male', b'0'),
	(207, 'Flory', 'Pietranek', '2127 Straubel Drive', 'Male', b'0'),
	(208, 'Reade', 'M\'cowis', '462 Grayhawk Crossing', 'Male', b'1'),
	(209, 'Claudelle', 'Ladyman', '27148 Hintze Court', 'Female', b'0'),
	(210, 'Elnar', 'Trahar', '78210 Valley Edge Terrace', 'Male', b'1'),
	(211, 'Sully', 'Jess', '17 Northridge Road', 'Male', b'1'),
	(212, 'Irwin', 'Extil', '60736 1st Lane', 'Male', b'1'),
	(213, 'Jordan', 'Yakovitch', '990 Randy Plaza', 'Female', b'0'),
	(214, 'Myca', 'Duffill', '370 Kipling Plaza', 'Male', b'1'),
	(215, 'Art', 'Beed', '60228 Dawn Parkway', 'Male', b'0'),
	(216, 'Odetta', 'Annatt', '19494 Hayes Court', 'Female', b'0'),
	(217, 'Dorri', 'Bedle', '5 Barby Way', 'Female', b'1'),
	(218, 'Cory', 'Blondin', '99 Crest Line Lane', 'Female', b'1'),
	(219, 'Gare', 'Eakens', '274 Rigney Pass', 'Male', b'1'),
	(220, 'Suki', 'Kmietsch', '67 Bluejay Parkway', 'Female', b'1'),
	(221, 'Athene', 'Baus', '5 Bartillon Pass', 'Female', b'1'),
	(222, 'Sharl', 'Weavill', '09 Vernon Point', 'Female', b'1'),
	(223, 'Milli', 'Lohrensen', '8278 Blue Bill Park Plaza', 'Female', b'1'),
	(224, 'Christopher', 'Kliemke', '750 Swallow Alley', 'Male', b'0'),
	(225, 'Casie', 'Cogman', '7239 Chive Place', 'Female', b'1'),
	(226, 'Helaine', 'Linklater', '3145 Waubesa Terrace', 'Female', b'0'),
	(227, 'Ransell', 'Samsworth', '70 Kim Center', 'Male', b'1'),
	(228, 'Adolpho', 'Durrans', '726 Lakeland Trail', 'Male', b'1'),
	(229, 'Regina', 'Pape', '55 Schurz Lane', 'Female', b'0'),
	(230, 'Carmita', 'Rowan', '1114 Hoard Point', 'Female', b'1'),
	(231, 'Nanci', 'Yushkov', '58245 Coleman Center', 'Female', b'1'),
	(232, 'Sanford', 'Geke', '56784 Roxbury Street', 'Male', b'0'),
	(233, 'Mack', 'Alsopp', '43505 Pearson Lane', 'Male', b'0'),
	(234, 'Ewell', 'Tennick', '2143 Basil Place', 'Male', b'0'),
	(235, 'Eduard', 'Haime', '12170 Surrey Trail', 'Male', b'0'),
	(236, 'Willard', 'Ansett', '990 Fairfield Plaza', 'Male', b'0'),
	(237, 'Hayden', 'Larvin', '03 Longview Road', 'Male', b'0'),
	(238, 'Ariadne', 'Ickovits', '343 Eagan Drive', 'Female', b'0'),
	(239, 'Gregorio', 'Snazel', '16 Hudson Plaza', 'Male', b'0'),
	(240, 'Zitella', 'Meates', '9 Norway Maple Plaza', 'Female', b'1'),
	(241, 'Terrye', 'Harewood', '72477 Marquette Pass', 'Female', b'1'),
	(242, 'Cirillo', 'Balk', '007 Meadow Ridge Junction', 'Male', b'1'),
	(243, 'Skylar', 'Barrow', '627 Loomis Circle', 'Male', b'0'),
	(244, 'Feodor', 'Digwood', '1 Victoria Center', 'Male', b'1'),
	(245, 'Doro', 'Blincoe', '316 Walton Way', 'Female', b'0'),
	(246, 'Willabella', 'Pigdon', '865 Bayside Terrace', 'Female', b'1'),
	(247, 'Dar', 'Mangenot', '2977 Spohn Drive', 'Male', b'0'),
	(248, 'Clare', 'Unsworth', '94 Ridgeway Way', 'Male', b'1'),
	(249, 'Creighton', 'Kairns', '303 Beilfuss Center', 'Male', b'0'),
	(250, 'Syman', 'Garretts', '29808 Transport Lane', 'Male', b'0'),
	(251, 'Beth', 'Ead', '43 Melvin Park', 'Female', b'1'),
	(252, 'Virgina', 'Niles', '2 Schurz Hill', 'Female', b'0'),
	(253, 'Giorgi', 'Pear', '2392 Merchant Center', 'Male', b'0'),
	(254, 'Malena', 'Dews', '1596 Donald Pass', 'Female', b'0'),
	(255, 'Gladi', 'Labern', '217 Aberg Hill', 'Female', b'1'),
	(256, 'Galvin', 'Pennyman', '08 Glacier Hill Circle', 'Male', b'1'),
	(257, 'Jorge', 'Dagon', '670 Toban Drive', 'Male', b'1'),
	(258, 'Stu', 'Wevell', '3734 Glacier Hill Street', 'Male', b'0'),
	(259, 'Quint', 'Keith', '96134 Thierer Alley', 'Male', b'1'),
	(260, 'Malynda', 'Elies', '72 Center Street', 'Female', b'0'),
	(261, 'Fredrika', 'McKie', '9 Eastlawn Trail', 'Female', b'1'),
	(262, 'Edwina', 'Hilbourne', '96972 Eggendart Junction', 'Female', b'1'),
	(263, 'Katy', 'O\'Cleary', '17356 Mayer Drive', 'Female', b'1'),
	(264, 'Rivkah', 'Doblin', '0164 Roth Terrace', 'Female', b'1'),
	(265, 'Skipper', 'Duck', '11543 Summerview Drive', 'Male', b'1'),
	(266, 'Eli', 'Mollindinia', '76081 Pawling Avenue', 'Male', b'1'),
	(267, 'Terencio', 'Petegre', '55 Lakewood Gardens Way', 'Male', b'0'),
	(268, 'Hobard', 'Orteaux', '4 Eastwood Place', 'Male', b'1'),
	(269, 'Nefen', 'Emerine', '6450 Waubesa Alley', 'Male', b'1'),
	(270, 'Elwood', 'Lilywhite', '1 Stephen Hill', 'Male', b'1'),
	(271, 'Farleigh', 'Golder', '808 Loomis Hill', 'Male', b'1'),
	(272, 'Dario', 'Arbuckel', '14 Kensington Place', 'Male', b'0'),
	(273, 'Dorelia', 'Kondrat', '2 3rd Crossing', 'Female', b'1'),
	(274, 'Erica', 'Timbridge', '0200 Carioca Circle', 'Female', b'1'),
	(275, 'Dalli', 'Hendrikse', '84 Rutledge Avenue', 'Male', b'0'),
	(276, 'Andree', 'Flaxman', '2762 Bashford Drive', 'Female', b'1'),
	(277, 'Donielle', 'Arger', '486 Mccormick Drive', 'Female', b'0'),
	(278, 'Tanny', 'Mars', '53217 Chive Street', 'Male', b'1'),
	(279, 'Thoma', 'Cripwell', '61 Colorado Plaza', 'Male', b'1'),
	(280, 'Wallie', 'Bolduc', '73 Sommers Road', 'Male', b'0'),
	(281, 'Burk', 'Todeo', '8662 Eagan Junction', 'Male', b'0'),
	(282, 'Cassandra', 'Courteney', '21915 Katie Terrace', 'Female', b'0'),
	(283, 'Suzie', 'Jickles', '72298 Old Gate Place', 'Female', b'1'),
	(284, 'Patsy', 'Durden', '457 Autumn Leaf Hill', 'Male', b'1'),
	(285, 'Bengt', 'Craig', '2 Bartillon Trail', 'Male', b'0'),
	(286, 'Ricoriki', 'Castillon', '86024 Oneill Court', 'Male', b'0'),
	(287, 'Tybie', 'Van Der Straaten', '3 Mallory Junction', 'Female', b'1'),
	(288, 'Fons', 'Messom', '18 Knutson Junction', 'Male', b'1'),
	(289, 'Bobbe', 'Gorvin', '090 Montana Junction', 'Female', b'1'),
	(290, 'Edward', 'Grealy', '4 Lyons Place', 'Male', b'1'),
	(291, 'Dyanna', 'Norledge', '09 Gale Junction', 'Female', b'1'),
	(292, 'Shepard', 'Crocket', '00528 Nevada Lane', 'Male', b'0'),
	(293, 'Cleo', 'Dunbar', '4 Norway Maple Terrace', 'Female', b'1'),
	(294, 'Dene', 'Gorch', '23571 Hooker Lane', 'Male', b'0'),
	(295, 'Kathryne', 'Sogg', '839 Brown Drive', 'Female', b'0'),
	(296, 'Cher', 'Scrivner', '67965 Vernon Hill', 'Female', b'1'),
	(297, 'Wrennie', 'Moulster', '13 Merchant Drive', 'Female', b'1'),
	(298, 'Stanwood', 'Szabo', '145 Vermont Circle', 'Male', b'0'),
	(299, 'Ax', 'Lapidus', '4032 Loftsgordon Place', 'Male', b'0'),
	(300, 'Ilyssa', 'Guillford', '5 Independence Point', 'Female', b'0'),
	(301, 'Jilly', 'McLucky', '7739 Graedel Trail', 'Female', b'0'),
	(302, 'Silvan', 'Bariball', '9 Basil Street', 'Male', b'1'),
	(303, 'Keane', 'Rodriguez', '26 Kinsman Park', 'Male', b'0'),
	(304, 'Grady', 'Balkwill', '43 Hooker Alley', 'Male', b'1'),
	(305, 'Bronson', 'Seven', '862 Nobel Point', 'Male', b'1');

-- Copiando dados para a tabela blogdogabu_db.posts: ~55 rows (aproximadamente)
INSERT INTO `posts` (`id`, `descricao`, `titulo`, `arq`, `file_name`, `enabled`) VALUES
	(1, 'Big Data: você provavelmente já ouviu falar nisso, não é mesmo? Mas, você sabe o que significa? De onde surgiu? Por que se fala tanto sobre nos últimos anos e porque as empresas do mundo todo tem os olhos voltados para ela?\n\nBem, o termo está diretamente relacionado aos dados gerados por pessoas e também empresas diariamente. Para você ter ideia, estima-se que sejam gerados diariamente 2,5 quintilhões de bytes de dados, segundo a IDC. Essas informações não são apenas organizacionais, mas também refletem o comportamento do seu potencial cliente.\n\nNão é à toa que os dados estão sendo chamados de “o novo petróleo”. Afinal, na atualidade, quem tem informação tem também mais opções de estratégias. Dessa forma, com a evolução da tecnologia e a transformação digital, vão surgindo novas formas de analisar esses dados e transformá-los em serviços diferenciados.\n\nMas a verdade é que o Big Data já existe até mesmo antes da popularização dos meios digitais. Por isso, veja neste artigo completo o que é Big Data, como ele surgiu e como funciona!', 'Big Data', NULL, NULL, 0),
	(2, 'Big Data: você provavelmente já ouviu falar nisso, não é mesmo? Mas, você sabe o que significa? De onde surgiu? Por que se fala tanto sobre nos últimos anos e porque as empresas do mundo todo tem os olhos voltados para ela?\n\nBem, o termo está diretamente relacionado aos dados gerados por pessoas e também empresas diariamente. Para você ter ideia, estima-se que sejam gerados diariamente 2,5 quintilhões de bytes de dados, segundo a IDC. Essas informações não são apenas organizacionais, mas também refletem o comportamento do seu potencial cliente.\n\nNão é à toa que os dados estão sendo chamados de “o novo petróleo”. Afinal, na atualidade, quem tem informação tem também mais opções de estratégias. Dessa forma, com a evolução da tecnologia e a transformação digital, vão surgindo novas formas de analisar esses dados e transformá-los em serviços diferenciados.\n\nMas a verdade é que o Big Data já existe até mesmo antes da popularização dos meios digitais. Por isso, veja neste artigo completo o que é Big Data, como ele surgiu e como funciona!', 'Big data', NULL, NULL, 0),
	(3, 'Aurora Aksnes (Stavanger, 15 de junho de 1996), conhecida profissionalmente apenas como Aurora e às vezes estilizado em caixa alta como AURORA, é uma cantora e compositora norueguesa.[2] Seu EP de estreia "Running with the Wolves" foi lançado pela gravadora Decca Records em maio de 2015,[3] recebendo grande aprovação de blogueiros de música e da imprensa. A artista já gravou dois covers de maior visibilidade, o primeiro de "Half the World Away", da banda Oasis, para uma propaganda Natalina de John Lewis e o segundo cover da música "Nature Boy" de Nat King Cole.[4] Ganhou algum maior reconhecimento a partir de uma publicação de Katy Perry ao dizer que havia gostado da música "Runaway".[5]', 'Aurora', NULL, NULL, 0),
	(4, 'a', 'Aurora', NULL, NULL, 0),
	(5, 'With software products being more and more just a bunch of micro-services and third-party APIs mashed together, it gets more crucial for us to get their structure in order.\n\nGraphQL already did this at its inception by coming with a whole specification that describes how APIs of its type should behave. In the RESTful API landscape, things went a bit more wild-west. However, even if not all backend devs know, there are various specifications for REST APIs too!\n\nOne of the best known is the OpenAPI spec or short OAS.\n\nEnter OpenAPIPermalink\nThe OpenAPI specification was known as Swagger until version 3.0 got released in 2017 and it was renamed to OpenAPI. It’s a language-agnostic way to describe a RESTful API that can be used to generate code-stubs and documentation.\n\nIts idea is to specify a REST API with a YAML document. This document can be used to generate documentation and methods for API endpoints. While APIs are generally used to decouple software, the OpenAPI spec also allows us to decouple the public interface of our API from our implementation details.\n\nBusiness and design teams can define the features they need, and an engineering team can create an OpenAPI YAML document that defines all these in technical terms.\n\nas a corner-stone to do their implementation. Both able to choose their technologies as they see fit.\n\nThe OpenAPI ecosystem even provides tools to create mock APIs, so the frontend developers have something more practical to work with.\n\nWhy should we use it?Permalink\nThere are a bunch of reasons why adding an OpenAPI specification between frontend and backend can be valuable.\n\nDesign-FirstPermalink\nWe can define the whole API with types and examples for every endpoint before we start implementing it. With tools that generate mock-APIs, we can verify that everything looks the way we intended. We can refine our API design by simply iterating over the specification document.\n\nCode GeneratorsPermalink\nOpenAPI is the REST specification with the most languages supported by their code-generators. It generates server stubs in the language of our choice, and we have to wire it up with our backend services and databases.\n\nToolingPermalink\nThe Swagger specification got donated to the OpenAPI foundation and renamed to OpenAPI specification. However, there is a giant ecosystem of tools created under the Swagger brand that can be used to speed up the API development process.\n\nThey can be used to generate automatically:\n\ndocumentation\ntests\nmock servers\nHuge UserbasePermalink\nOpenAPI is used and backed by many big companies and can be seen as their condensed knowledge of building thousands of APIs over the years. This knowledge alone is invaluable if we start out building our first API, but it’s also good to know that there are many people out there to help if something isn’t bright.\n\nStable ImplementationPermalink\nAs already mentioned, the OpenAPI spec was known as Swagger spec until 2017, so it doesn’t surprise that it isn’t the first version of the spec. It’s version 3.0 where the rebrand from Swagger to OpenAPI happened.\n\nThe spec doesn’t change too often now and can be considered mature at this point.\n\nWhy we should not use it?Permalink\nThe OpenAPI specification isn’t a silver bullet that can solve all problems that arise when building an API.\n\nNo RESTful APIPermalink\nIf we use GraphQL, we don’t need OpenAPI. However, sometimes it isn’t so obvious. Sometimes we get the task to build an API, think it will be RESTful, but when learning about the features that are needed, we are better off with something non-RESTful.\n\nIf we build, for example, an event-based system, something like gRPC or AsyncAPI may be a better fit for it.\n\nAdded ComplexityPermalink\nAs with all tools we add to our projects, there is the risk of added complexity that doesn’t bring any benefits. Many people got burned by SOAP in the past, even if the OpenAPI spec isn’t as massive, it can lead to problems when not used correctly.\n\nWe need to find some integration for the framework of our choice, or we need to switch to a framework that supports OpenAPI specifications. Then we could find out that the performance of the other framework isn’t good enough or it’s not maintained anymore.\n\nAlso, every line of code we write is a potential source of errors, even if it is YAML.\n\nThe developers building the API also have to acquire the skills to use OpenAPI, and it’s tools.\n\nSubstituting Missing SkillsPermalink\nOpenAPI can be overkill when we already got senior API devs who know their trade, but it can help to be a guideline for less experienced devs. The problem is, we need to train these people and not just hope OpenAPI will save us from lousy API design choices.\n\nIt should be a tool to help people and not a replacement for educating them.\n\nToolsPermalink\nThere is an ample supply of tooling to make work with OpenAPI even simpler. Converters, data-validators, documentation, editors, mock-servers, and generators for tests and SDKs.\n\nMost of it can be found here: https://openapi.tools/.\n\nAlternatives?Permalink\nThere are, of course, many alternatives to the OpenAPI spec, while they have lower adoption rate, it could be that they are pushing just the right buttons of our developers and are easier to understand and use.\n\nRAML - The RESTful API Modeling Language RAML is a bit more lightweight than OpenAPI but still based on YAML.\nAPI Blueprint. A powerful high-level API description language for web APIs. API Blueprint uses its own (non-YAML) syntax.\nConclusionPermalink\nOpenAPI is one of may attempts of casting decades of API building skills into a specification. Seemingly even the one with the most mind-share and money behind it.\n\nThe OpenAPI Initiative is part of the Linux Foundation, which makes it a bit more trustworthy and at least look like it won’t go away soon.\n\nIt isn’t a silver bullet and probably not for everyone, but if used right, the added complexity can save quite a bit time in documentation writing and test creation later.', 'Swagger', NULL, NULL, 0),
	(6, 'With software products being more and more just a bunch of micro-services and third-party APIs mashed together, it gets more crucial for us to get their structure in order.\n\nGraphQL already did this at its inception by coming with a whole specification that describes how APIs of its type should behave. In the RESTful API landscape, things went a bit more wild-west. However, even if not all backend devs know, there are various specifications for REST APIs too!\n\nOne of the best known is the OpenAPI spec or short OAS.\n\nEnter OpenAPIPermalink\nThe OpenAPI specification was known as Swagger until version 3.0 got released in 2017 and it was renamed to OpenAPI. It’s a language-agnostic way to describe a RESTful API that can be used to generate code-stubs and documentation.\n\nIts idea is to specify a REST API with a YAML document. This document can be used to generate documentation and methods for API endpoints. While APIs are generally used to decouple software, the OpenAPI spec also allows us to decouple the public interface of our API from our implementation details.\n\nBusiness and design teams can define the features they need, and an engineering team can create an OpenAPI YAML document that defines all these in technical terms.\n\nas a corner-stone to do their implementation. Both able to choose their technologies as they see fit.\n\nThe OpenAPI ecosystem even provides tools to create mock APIs, so the frontend developers have something more practical to work with.\n\nWhy should we use it?Permalink\nThere are a bunch of reasons why adding an OpenAPI specification between frontend and backend can be valuable.\n\nDesign-FirstPermalink\nWe can define the whole API with types and examples for every endpoint before we start implementing it. With tools that generate mock-APIs, we can verify that everything looks the way we intended. We can refine our API design by simply iterating over the specification document.\n\nCode GeneratorsPermalink\nOpenAPI is the REST specification with the most languages supported by their code-generators. It generates server stubs in the language of our choice, and we have to wire it up with our backend services and databases.\n\nToolingPermalink\nThe Swagger specification got donated to the OpenAPI foundation and renamed to OpenAPI specification. However, there is a giant ecosystem of tools created under the Swagger brand that can be used to speed up the API development process.\n\nThey can be used to generate automatically:\n\ndocumentation\ntests\nmock servers\nHuge UserbasePermalink\nOpenAPI is used and backed by many big companies and can be seen as their condensed knowledge of building thousands of APIs over the years. This knowledge alone is invaluable if we start out building our first API, but it’s also good to know that there are many people out there to help if something isn’t bright.\n\nStable ImplementationPermalink\nAs already mentioned, the OpenAPI spec was known as Swagger spec until 2017, so it doesn’t surprise that it isn’t the first version of the spec. It’s version 3.0 where the rebrand from Swagger to OpenAPI happened.\n\nThe spec doesn’t change too often now and can be considered mature at this point.\n\nWhy we should not use it?Permalink\nThe OpenAPI specification isn’t a silver bullet that can solve all problems that arise when building an API.\n\nNo RESTful APIPermalink\nIf we use GraphQL, we don’t need OpenAPI. However, sometimes it isn’t so obvious. Sometimes we get the task to build an API, think it will be RESTful, but when learning about the features that are needed, we are better off with something non-RESTful.\n\nIf we build, for example, an event-based system, something like gRPC or AsyncAPI may be a better fit for it.\n\nAdded ComplexityPermalink\nAs with all tools we add to our projects, there is the risk of added complexity that doesn’t bring any benefits. Many people got burned by SOAP in the past, even if the OpenAPI spec isn’t as massive, it can lead to problems when not used correctly.\n\nWe need to find some integration for the framework of our choice, or we need to switch to a framework that supports OpenAPI specifications. Then we could find out that the performance of the other framework isn’t good enough or it’s not maintained anymore.\n\nAlso, every line of code we write is a potential source of errors, even if it is YAML.\n\nThe developers building the API also have to acquire the skills to use OpenAPI, and it’s tools.\n\nSubstituting Missing SkillsPermalink\nOpenAPI can be overkill when we already got senior API devs who know their trade, but it can help to be a guideline for less experienced devs. The problem is, we need to train these people and not just hope OpenAPI will save us from lousy API design choices.\n\nIt should be a tool to help people and not a replacement for educating them.\n\nToolsPermalink\nThere is an ample supply of tooling to make work with OpenAPI even simpler. Converters, data-validators, documentation, editors, mock-servers, and generators for tests and SDKs.\n\nMost of it can be found here: https://openapi.tools/.\n\nAlternatives?Permalink\nThere are, of course, many alternatives to the OpenAPI spec, while they have lower adoption rate, it could be that they are pushing just the right buttons of our developers and are easier to understand and use.\n\nRAML - The RESTful API Modeling Language RAML is a bit more lightweight than OpenAPI but still based on YAML.\nAPI Blueprint. A powerful high-level API description language for web APIs. API Blueprint uses its own (non-YAML) syntax.\nConclusionPermalink\nOpenAPI is one of may attempts of casting decades of API building skills into a specification. Seemingly even the one with the most mind-share and money behind it.\n\nThe OpenAPI Initiative is part of the Linux Foundation, which makes it a bit more trustworthy and at least look like it won’t go away soon.\n\nIt isn’t a silver bullet and probably not for everyone, but if used right, the added complexity can save quite a bit time in documentation writing and test creation later.', 'Swagger', NULL, NULL, 0),
	(7, 'teste', 'Aurora', NULL, NULL, 0),
	(8, 'teste', 'A', NULL, NULL, 0),
	(9, 'teste1', 'A', NULL, NULL, 0),
	(10, 'teste', 'teste', NULL, NULL, 0),
	(11, 'teste', 'teste', NULL, NULL, 0),
	(12, 'teste', '6teste', NULL, NULL, 0),
	(13, 'teste', 'teste', NULL, NULL, 0),
	(14, 'teste', 'testestes', NULL, NULL, 0),
	(15, 'teste', 'teste', NULL, NULL, 0),
	(16, 'teste', 'teste', NULL, NULL, 0),
	(17, 'teste', 'teste', NULL, NULL, 0),
	(18, 'testes', 'testew', NULL, NULL, 0),
	(19, 'teste', 'teste', NULL, NULL, 0),
	(20, 'estes', 'test', NULL, NULL, 0),
	(21, 'test', 'etest', NULL, NULL, 0),
	(22, 'teste', 'teste', NULL, NULL, 0),
	(23, 'teste', 'teste', NULL, NULL, 0),
	(24, 'teste', 'teste', NULL, NULL, 0),
	(25, 'teste', 'teste', NULL, NULL, 0),
	(26, 'teste', 'teste', NULL, NULL, 0),
	(27, 'teste', 'teste', NULL, 'stsci-01gq5chesabwmhrf5na60a6mpf_0.png', 0),
	(28, 'teste', 'teste', NULL, 'wjs_2270_orig.jpg', 0),
	(29, 'Testando', 'Testando', NULL, 'pia21590_orig.jpg', 0),
	(30, 'O que é exatamente big data?\n\nA definição de big data são dados que contêm maior variedade, chegando em volumes crescentes e com mais velocidade. Isso também é conhecido como os três Vs.\n\nSimplificando, big data é um conjunto de dados maior e mais complexo, especialmente de novas fontes de dados. Esses conjuntos de dados são tão volumosos que o software tradicional de processamento de dados simplesmente não consegue gerenciá-los. No entanto, esses grandes volumes de dados podem ser usados para resolver problemas de negócios que você não conseguiria resolver antes.', 'Big data', NULL, 'download.jpg', 0),
	(31, 'testando', 'A', NULL, 'pexels-pixabay-235621.jpg', 0),
	(32, 'estagiario', 'A', NULL, 'stsci-01gq5chesabwmhrf5na60a6mpf_0.png', 0),
	(33, 'B', 'A', NULL, 'pexels-pixabay-235621.jpg', 0),
	(34, 'teste', 'teste', NULL, 'pexels-pixabay-235621.jpg', 0),
	(35, 'Este é o primeiro post', 'Primeiro post', NULL, 'avatar.jpg', 0),
	(36, 'a', 'Sobre o Vue.js', NULL, 'download.png', 0),
	(37, 'O Bootstrap é uma ferramenta gratuita para desenvolvimento HTML, CSS e JS. Crie protótipos rápidamente ou aplicações completas com nossas variáveis e mixins Sass, sistemas de grid responsivo, componentes pré-construídos e poderosos plugins com jQuery.', 'Bootstrap', NULL, 'bootstrap.png', 1),
	(38, 'Frameworks são estruturas compostas por um conjunto de códigos genéricos que permite o desenvolvimento de sistemas e aplicações. Um framework funciona como uma espécie de template ou modelo que, quando utilizado, oferece certos artifícios e elementos estruturais básicos para a criação de alguma aplicação ou software.', 'Frameworks', NULL, '8-melhores-frameworks-de-desenvolvimento-web-em-2022.webp', 1),
	(39, 'teste', 'Teste', NULL, '8-melhores-frameworks-de-desenvolvimento-web-em-2022.webp', 0),
	(40, 'testes', 'Outro teste', NULL, '8-melhores-frameworks-de-desenvolvimento-web-em-2022.webp', 0),
	(41, 'teste', 'teste', NULL, '8-melhores-frameworks-de-desenvolvimento-web-em-2022.webp', 0),
	(42, 'yeste12', 'teste12', NULL, '8-melhores-frameworks-de-desenvolvimento-web-em-2022.webp', 0),
	(43, 'teste', 'Teste', NULL, '8-melhores-frameworks-de-desenvolvimento-web-em-2022.webp', 0),
	(44, 'teste', 'tesdte', NULL, '8-melhores-frameworks-de-desenvolvimento-web-em-2022.webp', 0),
	(45, 'testest', 'testest', NULL, 'download.jpg', 0),
	(46, 'teste', 'teste', NULL, 'download.jpg', 0),
	(47, 'b', 'a', NULL, 'download.jpg', 0),
	(48, 'v', 'a', NULL, 'download.png', 0),
	(49, 'ChatGPT é um protótipo de um chatbot com inteligência artificial desenvolvido pela OpenAI e especializado em diálogo. O chatbot é um modelo de linguagem ajustado com técnicas de aprendizado supervisionado e por reforço', 'ChatGPT', NULL, 'gpt.jpg', 1),
	(50, 'DALL-E é um programa de inteligência artificial que cria imagens a partir de descrições textuais. Ele usa uma versão de 12 bilhões de parâmetros do modelo GPT-3 Transformer para interpretar entradas de linguagem natural e gerar imagens.', 'DALL-E', NULL, 'CxkQw5jSt836ejKfSixSAP-1200-80.jpg', 1),
	(51, 'GitHub é uma plataforma de hospedagem de código-fonte e arquivos com controle de versão usando o Git. Ele permite que programadores, utilitários ou qualquer usuário cadastrado na plataforma contribuam em projetos privados e/ou Open Source de qualquer lugar do mundo', 'GitHub', NULL, 'what-is-github-1-1.png', 1),
	(52, 'De automação do atendimento a cruzamento de dados e mapeamento de perfis de consumidores! Essa é a SharkData!\nA SharkData tem como principal objetivo proporcionar uma melhor experiência para os consumidores e usuários de seus clientes por meio de tecnologias voltadas ao resultado operacional e a diminuição do esforço do cliente.', 'SharkData', NULL, 'shark-mascote-positivo.120df9a.png', 1),
	(53, 'O Swagger é um framework composto por diversas ferramentas que, independente da linguagem, auxilia a descrição, consumo e visualização de serviços de uma API REST. \n\nNo framework Swagger, existem ferramentas para os seguintes tipos de tarefas a serem realizadas para o completo desenvolvimento da API de um serviço WEB: \n\n1) A especificação da API consiste em determinar os modelos de dados que serão entendidos pela API e as  funcionalidades presentes na mesma. Para cada funcionalidade, é preciso especificar o seu nome, os parâmetros que devem ser passados no momento de sua invocação e os valores que irão ser retornados aos usuários da API. Entre esta ferramentas, podemos citar o OpenAPI Specification.\n\n2) Após especificar a API, o framework facilita sua implementação, com a ferramenta Swagger Codegen é possível montar o código inicial automaticamente nas principais linguagem de programação.\n\n3) Os testes de API são extremamente importantes, pois ajudam a garantir o funcionamento, o desempenho e a confiabilidade da sua aplicação. O Swagger oferece ferramentas para teste manuais, automatizados e de desempenho \n\n4) Para auxiliar na utilização da API, o Swagger dispõe de ferramenta para deixar a visualização mais intuitiva, permitindo também que interajam com a API.\n\nO Swagger permite criar a documentação da API de 3 formas:\n\n1- Automaticamente: Simultaneamente ao desenvolvimento da API é gerada a documentação.\n\n2- Manualmente: Permite ao desenvolvedor escrever livremente as especificações da API e as publicar posteriormente em seu próprio servidor.\n\n3- Codegen: Converte todas as anotações contidas no código fonte das APIs REST em documentação.', 'Swagger', NULL, 'benefits-of-using-the-openapi-swagger-specification-for-your-api.png', 1),
	(54, 'A Unesp (Universidade Estadual Paulista) é uma das maiores e mais importantes universidades brasileiras, com destacada atuação no ensino, na pesquisa e na extensão de serviços à comunidade.\n\nMantida pelo governo do estado de São Paulo, é uma das três universidades públicas de ensino gratuito, ao lado da USP (Universidade de São Paulo) e da Unicamp (Universidade Estadual de Campinas).\n\nCriada em 1976, a partir da reunião de institutos isolados de ensino superior que existiam em várias regiões do estado de São Paulo, a Unesp tem 34 unidades em 24 cidades, sendo 22 no interior; uma na capital; e uma no litoral paulista, mais especificamente na cidade de São Vicente.', 'Unesp', NULL, 'tudo-sobre-a-unesp-F4.jpg', 1),
	(55, 'teste', 'teste', NULL, 'benefits-of-using-the-openapi-swagger-specification-for-your-api.png', 0);

-- Copiando dados para a tabela blogdogabu_db.users: ~2 rows (aproximadamente)
INSERT INTO `users` (`id`, `user_name`, `password`, `full_name`, `refresh_token`, `refresh_token_expiry_time`) VALUES
	(1, 'leandro', '24-0B-E5-18-FA-BD-27-24-DD-B6-F0-4E-EB-1D-A5-96-74-48-D7-E8-31-C0-8C-8F-A8-22-80-9F-74-C7-20-A9', 'LEANDRO DA COSTA GONCALVES', '/Y9AU4Ancc+AawBYLKSn+HORft6cO8UMoZR/Nc5EXpw=', '2023-02-23 12:29:53'),
	(2, 'gabu', '24-0B-E5-18-FA-BD-27-24-DD-B6-F0-4E-EB-1D-A5-96-74-48-D7-E8-31-C0-8C-8F-A8-22-80-9F-74-C7-20-A9', 'GABRIEL GONSALES BUGUE', 'bJ7OySKWkKU2W2S7BRSP9I09Ue70XdFxs5if8DS0Cm0=', '2023-03-01 13:51:11');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
